Missions:
  - ORBONE
  - CLNM
  - TMRS
  - GALAXONE
  - UNKN
DeviceType:
  - Satellite
  - Spacecraft
  - Spacesuit
  - Unknown
DeviceStatus:
  - excellent
  - good
  - warning
  - faulty
  - killed
  - unknown
num_loops: 2
num_files_per_loop: 100
time_to_create_file: 10
