Missions:
  - ORBONE
  - CLNM
  - TMRS
  - GALAXONE
  - UNKN
DeviceType:
  - Satellite
  - Spacecraft
  - Spacesuit
  - Unknown
DeviceStatus:
  - excellent
  - good
  - warning
  - faulty
  - killed
  - unknown
range_for_files: False
min_files_per_loop: 10
max_files_per_loop: 100
infinity_loops: False
num_loops: 3
time_to_create_file: 2

