Missions:
  - ORBONE
  - CLNM
  - TMRS
  - GALAXONE
  - UNKN
DeviceType:
  - Satellite
  - Spacecraft
  - Spacesuit
  - Unknown
DeviceStatus:
  - excellent
  - good
  - warning
  - faulty
  - killed
  - unknown


#---------------------------------------------------------------------------

#This part is shared among the three ways to run the program:
#range_for_files defines the quantity of files that will be generated during the execution
# If range_for_files is TRUE, you need to use min_files_per_loop and max_files_per_loop to generate a random number between these two
# If range_for_files is FALSE, you need to use only max_files_per_loop to generate a random number between 0 and max_files_per_loop

range_for_files: False 
min_files_per_loop: 10 
max_files_per_loop: 15 

#---------------------------------------------------------------------------

#First way to execute program: When you want to execute the program for an specific time:
# infinity_loops must be FALSE
# time_execution_second must be greater than 0

execute_by_time: True 
time_execution_second: 5

#---------------------------------------------------------------------------

# Second way to run the program: When you want to have inifity loops, and you want the system to create files indefinitely. 
# execute_by_time must be FALSE

infinity_loops: False 

#---------------------------------------------------------------------------
#Third way to run the program: When you want to run the program by a number of designated loops
# infinity_loops must be FALSE
# execute_by_time must be FALSE
# num_loop must be greater than 0

num_loops: 2 
time_to_create_file: 1

#---------------------------------------------------------------------------

